/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.ifba.ipss.feature.widget.model;

/**
 *
 * @author curso
 */
public class CaixaDeFerramentasVavulas extends javax.swing.JPanel {

    /**
     * Creates new form CaixaDeFerramentasVavulas
     */
    public CaixaDeFerramentasVavulas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        pnlBackground = new javax.swing.JPanel();
        pnlVavula4 = new javax.swing.JPanel();
        lblVavula4 = new javax.swing.JLabel();
        lblVavulas = new javax.swing.JLabel();
        pnlVavula1 = new javax.swing.JPanel();
        lblVavula1 = new javax.swing.JLabel();
        pnlVavula3 = new javax.swing.JPanel();
        lblVavula3 = new javax.swing.JLabel();
        pnlVavula2 = new javax.swing.JPanel();
        lblVavula2 = new javax.swing.JLabel();
        pnlVavula5 = new javax.swing.JPanel();
        lblVavula5 = new javax.swing.JLabel();

        setLayout(null);

        jPanel3.setLayout(null);

        pnlBackground.setBackground(new java.awt.Color(102, 102, 102));
        pnlBackground.setLayout(null);

        pnlVavula4.setBackground(new java.awt.Color(204, 204, 204));
        pnlVavula4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlVavula4.setForeground(new java.awt.Color(255, 255, 255));

        lblVavula4.setText("Vávula 4");

        javax.swing.GroupLayout pnlVavula4Layout = new javax.swing.GroupLayout(pnlVavula4);
        pnlVavula4.setLayout(pnlVavula4Layout);
        pnlVavula4Layout.setHorizontalGroup(
            pnlVavula4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVavula4Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(lblVavula4)
                .addGap(23, 23, 23))
        );
        pnlVavula4Layout.setVerticalGroup(
            pnlVavula4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVavula4Layout.createSequentialGroup()
                .addComponent(lblVavula4)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        pnlBackground.add(pnlVavula4);
        pnlVavula4.setBounds(140, 270, 90, 90);

        lblVavulas.setForeground(new java.awt.Color(255, 255, 255));
        lblVavulas.setText("VÁVULAS");
        pnlBackground.add(lblVavulas);
        lblVavulas.setBounds(120, 110, 50, 16);

        pnlVavula1.setBackground(new java.awt.Color(204, 204, 204));
        pnlVavula1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlVavula1.setForeground(new java.awt.Color(255, 255, 255));

        lblVavula1.setText("Vávula 1");

        javax.swing.GroupLayout pnlVavula1Layout = new javax.swing.GroupLayout(pnlVavula1);
        pnlVavula1.setLayout(pnlVavula1Layout);
        pnlVavula1Layout.setHorizontalGroup(
            pnlVavula1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVavula1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblVavula1)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlVavula1Layout.setVerticalGroup(
            pnlVavula1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVavula1Layout.createSequentialGroup()
                .addComponent(lblVavula1)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        pnlBackground.add(pnlVavula1);
        pnlVavula1.setBounds(50, 180, 90, 90);

        pnlVavula3.setBackground(new java.awt.Color(204, 204, 204));
        pnlVavula3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlVavula3.setForeground(new java.awt.Color(255, 255, 255));

        lblVavula3.setText("Vávula 3");

        javax.swing.GroupLayout pnlVavula3Layout = new javax.swing.GroupLayout(pnlVavula3);
        pnlVavula3.setLayout(pnlVavula3Layout);
        pnlVavula3Layout.setHorizontalGroup(
            pnlVavula3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVavula3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblVavula3)
                .addGap(21, 21, 21))
        );
        pnlVavula3Layout.setVerticalGroup(
            pnlVavula3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVavula3Layout.createSequentialGroup()
                .addComponent(lblVavula3)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        pnlBackground.add(pnlVavula3);
        pnlVavula3.setBounds(50, 270, 90, 90);

        pnlVavula2.setBackground(new java.awt.Color(204, 204, 204));
        pnlVavula2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlVavula2.setForeground(new java.awt.Color(255, 255, 255));

        lblVavula2.setText("Vávula 2");

        javax.swing.GroupLayout pnlVavula2Layout = new javax.swing.GroupLayout(pnlVavula2);
        pnlVavula2.setLayout(pnlVavula2Layout);
        pnlVavula2Layout.setHorizontalGroup(
            pnlVavula2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVavula2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblVavula2)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlVavula2Layout.setVerticalGroup(
            pnlVavula2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVavula2Layout.createSequentialGroup()
                .addComponent(lblVavula2)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        pnlBackground.add(pnlVavula2);
        pnlVavula2.setBounds(140, 180, 90, 90);

        pnlVavula5.setBackground(new java.awt.Color(204, 204, 204));
        pnlVavula5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlVavula5.setForeground(new java.awt.Color(255, 255, 255));

        lblVavula5.setText("Vávula 5");

        javax.swing.GroupLayout pnlVavula5Layout = new javax.swing.GroupLayout(pnlVavula5);
        pnlVavula5.setLayout(pnlVavula5Layout);
        pnlVavula5Layout.setHorizontalGroup(
            pnlVavula5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVavula5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblVavula5)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlVavula5Layout.setVerticalGroup(
            pnlVavula5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVavula5Layout.createSequentialGroup()
                .addComponent(lblVavula5)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        pnlBackground.add(pnlVavula5);
        pnlVavula5.setBounds(50, 360, 90, 90);

        jPanel3.add(pnlBackground);
        pnlBackground.setBounds(0, 0, 280, 820);

        add(jPanel3);
        jPanel3.setBounds(280, 0, 280, 820);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblVavula1;
    private javax.swing.JLabel lblVavula2;
    private javax.swing.JLabel lblVavula3;
    private javax.swing.JLabel lblVavula4;
    private javax.swing.JLabel lblVavula5;
    private javax.swing.JLabel lblVavulas;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlVavula1;
    private javax.swing.JPanel pnlVavula2;
    private javax.swing.JPanel pnlVavula3;
    private javax.swing.JPanel pnlVavula4;
    private javax.swing.JPanel pnlVavula5;
    // End of variables declaration//GEN-END:variables
}
