/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.ifba.ipss.feature.widget.model;

/**
 *
 * @author curso
 */
public class CaixaDeFerramentasEquipamentos extends javax.swing.JPanel {

    /**
     * Creates new form CaixaDeFerramentasEquipamentos
     */
    public CaixaDeFerramentasEquipamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlBackground = new javax.swing.JPanel();
        lblReatorTanque = new javax.swing.JLabel();
        pnlTrocadorDeCalor = new javax.swing.JPanel();
        pnlBomba3 = new javax.swing.JPanel();
        lblBomba3 = new javax.swing.JLabel();
        lblBomba = new javax.swing.JLabel();
        pnlBomba1 = new javax.swing.JPanel();
        lblBomba1 = new javax.swing.JLabel();
        lblTorresDeDestilaçõaResfriamento = new javax.swing.JLabel();
        pnlReator = new javax.swing.JPanel();
        lblReator = new javax.swing.JLabel();
        lblTrocadorDECalor = new javax.swing.JLabel();
        pnlBomba2 = new javax.swing.JPanel();
        lblBomba2 = new javax.swing.JLabel();
        pnlTanque = new javax.swing.JPanel();
        lblTanque = new javax.swing.JLabel();
        pnlTorreDeResfriamento = new javax.swing.JPanel();
        lblResfriamento = new javax.swing.JLabel();
        pnlTorreDeDestilacao = new javax.swing.JPanel();
        lblDestilacao = new javax.swing.JLabel();
        lblEquipamentos = new javax.swing.JLabel();

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 820));
        jPanel1.setLayout(null);

        pnlBackground.setBackground(new java.awt.Color(102, 102, 102));
        pnlBackground.setLayout(null);

        lblReatorTanque.setBackground(new java.awt.Color(255, 255, 255));
        lblReatorTanque.setForeground(new java.awt.Color(255, 255, 255));
        lblReatorTanque.setText("Reator/Tanque");
        pnlBackground.add(lblReatorTanque);
        lblReatorTanque.setBounds(100, 390, 80, 16);

        pnlTrocadorDeCalor.setBackground(new java.awt.Color(204, 204, 204));
        pnlTrocadorDeCalor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTrocadorDeCalor.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlTrocadorDeCalorLayout = new javax.swing.GroupLayout(pnlTrocadorDeCalor);
        pnlTrocadorDeCalor.setLayout(pnlTrocadorDeCalorLayout);
        pnlTrocadorDeCalorLayout.setHorizontalGroup(
            pnlTrocadorDeCalorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        pnlTrocadorDeCalorLayout.setVerticalGroup(
            pnlTrocadorDeCalorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        pnlBackground.add(pnlTrocadorDeCalor);
        pnlTrocadorDeCalor.setBounds(100, 720, 90, 90);

        pnlBomba3.setBackground(new java.awt.Color(204, 204, 204));
        pnlBomba3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlBomba3.setForeground(new java.awt.Color(255, 255, 255));

        lblBomba3.setText("Bomba 3");

        javax.swing.GroupLayout pnlBomba3Layout = new javax.swing.GroupLayout(pnlBomba3);
        pnlBomba3.setLayout(pnlBomba3Layout);
        pnlBomba3Layout.setHorizontalGroup(
            pnlBomba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBomba3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblBomba3)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlBomba3Layout.setVerticalGroup(
            pnlBomba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBomba3Layout.createSequentialGroup()
                .addComponent(lblBomba3)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        pnlBackground.add(pnlBomba3);
        pnlBomba3.setBounds(50, 270, 90, 90);

        lblBomba.setForeground(new java.awt.Color(255, 255, 255));
        lblBomba.setText("Bombas");
        pnlBackground.add(lblBomba);
        lblBomba.setBounds(120, 140, 50, 16);

        pnlBomba1.setBackground(new java.awt.Color(204, 204, 204));
        pnlBomba1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlBomba1.setForeground(new java.awt.Color(255, 255, 255));

        lblBomba1.setText(" Bomba 1");

        javax.swing.GroupLayout pnlBomba1Layout = new javax.swing.GroupLayout(pnlBomba1);
        pnlBomba1.setLayout(pnlBomba1Layout);
        pnlBomba1Layout.setHorizontalGroup(
            pnlBomba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBomba1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblBomba1)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlBomba1Layout.setVerticalGroup(
            pnlBomba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBomba1Layout.createSequentialGroup()
                .addComponent(lblBomba1)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        pnlBackground.add(pnlBomba1);
        pnlBomba1.setBounds(50, 180, 90, 90);

        lblTorresDeDestilaçõaResfriamento.setForeground(new java.awt.Color(255, 255, 255));
        lblTorresDeDestilaçõaResfriamento.setText("Torres de destilação/Resfriamento");
        pnlBackground.add(lblTorresDeDestilaçõaResfriamento);
        lblTorresDeDestilaçõaResfriamento.setBounds(50, 540, 220, 16);

        pnlReator.setBackground(new java.awt.Color(204, 204, 204));
        pnlReator.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlReator.setForeground(new java.awt.Color(255, 255, 255));

        lblReator.setText("Reator");

        javax.swing.GroupLayout pnlReatorLayout = new javax.swing.GroupLayout(pnlReator);
        pnlReator.setLayout(pnlReatorLayout);
        pnlReatorLayout.setHorizontalGroup(
            pnlReatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReatorLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(lblReator)
                .addGap(25, 25, 25))
        );
        pnlReatorLayout.setVerticalGroup(
            pnlReatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReatorLayout.createSequentialGroup()
                .addComponent(lblReator)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        pnlBackground.add(pnlReator);
        pnlReator.setBounds(50, 430, 90, 90);

        lblTrocadorDECalor.setForeground(new java.awt.Color(255, 255, 255));
        lblTrocadorDECalor.setText("Trocador de calor");
        pnlBackground.add(lblTrocadorDECalor);
        lblTrocadorDECalor.setBounds(100, 690, 100, 16);

        pnlBomba2.setBackground(new java.awt.Color(204, 204, 204));
        pnlBomba2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlBomba2.setForeground(new java.awt.Color(255, 255, 255));

        lblBomba2.setText("Bomba 2");

        javax.swing.GroupLayout pnlBomba2Layout = new javax.swing.GroupLayout(pnlBomba2);
        pnlBomba2.setLayout(pnlBomba2Layout);
        pnlBomba2Layout.setHorizontalGroup(
            pnlBomba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBomba2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblBomba2)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlBomba2Layout.setVerticalGroup(
            pnlBomba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBomba2Layout.createSequentialGroup()
                .addComponent(lblBomba2)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        pnlBackground.add(pnlBomba2);
        pnlBomba2.setBounds(140, 180, 90, 90);

        pnlTanque.setBackground(new java.awt.Color(204, 204, 204));
        pnlTanque.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTanque.setForeground(new java.awt.Color(255, 255, 255));

        lblTanque.setText("Tanque");

        javax.swing.GroupLayout pnlTanqueLayout = new javax.swing.GroupLayout(pnlTanque);
        pnlTanque.setLayout(pnlTanqueLayout);
        pnlTanqueLayout.setHorizontalGroup(
            pnlTanqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTanqueLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(lblTanque)
                .addGap(21, 21, 21))
        );
        pnlTanqueLayout.setVerticalGroup(
            pnlTanqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTanqueLayout.createSequentialGroup()
                .addComponent(lblTanque)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        pnlBackground.add(pnlTanque);
        pnlTanque.setBounds(140, 430, 90, 90);

        pnlTorreDeResfriamento.setBackground(new java.awt.Color(204, 204, 204));
        pnlTorreDeResfriamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTorreDeResfriamento.setForeground(new java.awt.Color(255, 255, 255));

        lblResfriamento.setText("Resfriamento");

        javax.swing.GroupLayout pnlTorreDeResfriamentoLayout = new javax.swing.GroupLayout(pnlTorreDeResfriamento);
        pnlTorreDeResfriamento.setLayout(pnlTorreDeResfriamentoLayout);
        pnlTorreDeResfriamentoLayout.setHorizontalGroup(
            pnlTorreDeResfriamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTorreDeResfriamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResfriamento)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pnlTorreDeResfriamentoLayout.setVerticalGroup(
            pnlTorreDeResfriamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTorreDeResfriamentoLayout.createSequentialGroup()
                .addComponent(lblResfriamento)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        pnlBackground.add(pnlTorreDeResfriamento);
        pnlTorreDeResfriamento.setBounds(140, 580, 90, 90);

        pnlTorreDeDestilacao.setBackground(new java.awt.Color(204, 204, 204));
        pnlTorreDeDestilacao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTorreDeDestilacao.setForeground(new java.awt.Color(255, 255, 255));

        lblDestilacao.setText("Destilação");

        javax.swing.GroupLayout pnlTorreDeDestilacaoLayout = new javax.swing.GroupLayout(pnlTorreDeDestilacao);
        pnlTorreDeDestilacao.setLayout(pnlTorreDeDestilacaoLayout);
        pnlTorreDeDestilacaoLayout.setHorizontalGroup(
            pnlTorreDeDestilacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTorreDeDestilacaoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblDestilacao)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pnlTorreDeDestilacaoLayout.setVerticalGroup(
            pnlTorreDeDestilacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTorreDeDestilacaoLayout.createSequentialGroup()
                .addComponent(lblDestilacao)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        pnlBackground.add(pnlTorreDeDestilacao);
        pnlTorreDeDestilacao.setBounds(50, 580, 90, 90);

        lblEquipamentos.setForeground(new java.awt.Color(255, 255, 255));
        lblEquipamentos.setText("EQUIPAMENTOS");
        pnlBackground.add(lblEquipamentos);
        lblEquipamentos.setBounds(100, 100, 88, 16);

        jPanel1.add(pnlBackground);
        pnlBackground.setBounds(-1, -3, 280, 820);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 168, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBomba;
    private javax.swing.JLabel lblBomba1;
    private javax.swing.JLabel lblBomba2;
    private javax.swing.JLabel lblBomba3;
    private javax.swing.JLabel lblDestilacao;
    private javax.swing.JLabel lblEquipamentos;
    private javax.swing.JLabel lblReator;
    private javax.swing.JLabel lblReatorTanque;
    private javax.swing.JLabel lblResfriamento;
    private javax.swing.JLabel lblTanque;
    private javax.swing.JLabel lblTorresDeDestilaçõaResfriamento;
    private javax.swing.JLabel lblTrocadorDECalor;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlBomba1;
    private javax.swing.JPanel pnlBomba2;
    private javax.swing.JPanel pnlBomba3;
    private javax.swing.JPanel pnlReator;
    private javax.swing.JPanel pnlTanque;
    private javax.swing.JPanel pnlTorreDeDestilacao;
    private javax.swing.JPanel pnlTorreDeResfriamento;
    private javax.swing.JPanel pnlTrocadorDeCalor;
    // End of variables declaration//GEN-END:variables
}
