// *************************************************//
// *************** { COMEÇO - Package } ************//
// *************************************************//
package br.com.ifba.ipss.view;
// *************************************************//
// *************** { FIM - Package } ***************//
// *************************************************//

// *************************************************//
// ************ { COMEÇO - Imports } ***************//
// *************************************************//
import br.com.ifba.ipss.common.controller.AreaDeTrabalhoController;
import br.com.ifba.ipss.common.controller.BotaoConectarController;
import br.com.ifba.ipss.common.controller.BotaoSimularController;
import br.com.ifba.ipss.common.controller.MenuFerramentasController;
import br.com.ifba.ipss.feature.conexao.domain.service.ConexaoServiceImpl;
import br.com.ifba.ipss.feature.conexao.domain.service.IConexaoService;
import br.com.ifba.ipss.helper.PathHelper;
import br.com.ifba.ipss.feature.tubulacao.domain.service.ITubulacaoService;
import br.com.ifba.ipss.feature.tubulacao.domain.service.TubulacaoServiceImpl;
import br.com.ifba.ipss.util.Constantes;
import br.com.ifba.ipss.util.NomeEquipamento;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
// *************************************************//
// ************** { FIM - Imports } ****************//
// *************************************************//

/**
 *
 * @author Giovane Neves
 * @since V0.0.1
 */
public class AreaDeTrabalho extends javax.swing.JFrame {

    
    // *************************************************//
    // ****************** { Atributos } ****************//
    // *************************************************//
    private AreaDeTrabalhoController areaDeTrabalhoController = new AreaDeTrabalhoController(this);
    
    private final MenuFerramentasController _menuFerramentasController;
    private final BotaoSimularController botaoSimularController;
    private final BotaoConectarController botaoConectarController;
    
    private final ITubulacaoService tubulacaoService = new TubulacaoServiceImpl();
    private final IConexaoService conexaoService = new ConexaoServiceImpl();
    
    public static boolean emModoRemocao = false;
    public static boolean emModoConexao = false;
    
    /**
     * Cria a interface com os componentes iniciais
     */
    public AreaDeTrabalho() {
        botaoSimularController = new BotaoSimularController();
        botaoConectarController = new BotaoConectarController();
        
        _menuFerramentasController = new MenuFerramentasController(pegarListaEquipamentos(PathHelper.FERRAMENTAS_JSON));
        
        inicializadorPersonalizado();
        initComponents();
        
        this.areaDeTrabalhoController.setPnlEspacoTrabalho(pnlEspacoTrabalho);
        
        List<javax.swing.JButton> botoes = List.of(
                btnGirarEquipamento,
                btnConectarEquipamentos,
                btnRemoverEquipamento,
                btnSimular,
                btnTubulacoes,
                btnConexoes,
                btnVavulas,
                btnEquipamentos
        );
        
        this.areaDeTrabalhoController.mudarSetaDoMouseNoBotao(botoes);
        
    } // AreaDeTrabalho

    public Map<String, List<?>> pegarListaEquipamentos(String caminho){
        
        Map<String, List<?>> equipamentos = new HashMap<>();
        
        equipamentos.put("Tubulações", tubulacaoService.pegarEquipamentos());
        equipamentos.put("Conexões", conexaoService.pegarEquipamentos());
        
        return equipamentos;
        
    } // pegarListEquipamentos
    
    private void inicializadorPersonalizado(){
        
        ImageIcon favicon = new ImageIcon(getClass().getResource(Constantes.CAMINHO_LOGO));
        this.areaDeTrabalhoController.definirLogoAplicacao(favicon.getImage());
        this.areaDeTrabalhoController.definirTituloAplicacao();
        
    } // inicializadorPersonalizado
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackgruond = new javax.swing.JPanel();
        PnlFixo = new javax.swing.JPanel();
        LabTítulo = new javax.swing.JLabel();
        PnlMenu = new javax.swing.JPanel();
        btnGirarEquipamento = new javax.swing.JButton();
        btnConectarEquipamentos = new javax.swing.JButton();
        btnRemoverEquipamento = new javax.swing.JButton();
        btnSimular = new javax.swing.JButton();
        btnLimparEspacoTrabalho = new javax.swing.JButton();
        btnSalvarEspacoTrabalho = new javax.swing.JButton();
        pnlEspacoTrabalho = new javax.swing.JPanel();
        lblNotificacaoDeEstado = new javax.swing.JLabel();
        PnlBotoes = new javax.swing.JPanel();
        btnTubulacoes = new javax.swing.JButton();
        btnConexoes = new javax.swing.JButton();
        btnEquipamentos = new javax.swing.JButton();
        btnVavulas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnlBackgruond.setBackground(new java.awt.Color(204, 204, 204));
        pnlBackgruond.setPreferredSize(new java.awt.Dimension(1300, 820));
        pnlBackgruond.setLayout(null);

        PnlFixo.setBackground(new java.awt.Color(0, 102, 51));

        LabTítulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabTítulo.setForeground(new java.awt.Color(255, 255, 255));
        LabTítulo.setText("EduSimLab - Laboratório Virtual de Simulação de Processos");
        PnlFixo.add(LabTítulo);

        pnlBackgruond.add(PnlFixo);
        PnlFixo.setBounds(0, 0, 1410, 30);

        PnlMenu.setBackground(new java.awt.Color(255, 255, 255));

        btnGirarEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao_girar.png"))); // NOI18N
        btnGirarEquipamento.setBorderPainted(false);
        btnGirarEquipamento.setContentAreaFilled(false);
        btnGirarEquipamento.setFocusPainted(false);
        btnGirarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirarEquipamentoActionPerformed(evt);
            }
        });

        btnConectarEquipamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao_conectar.png"))); // NOI18N
        btnConectarEquipamentos.setBorderPainted(false);
        btnConectarEquipamentos.setContentAreaFilled(false);
        btnConectarEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarEquipamentosActionPerformed(evt);
            }
        });

        btnRemoverEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao_remover.png"))); // NOI18N
        btnRemoverEquipamento.setBorderPainted(false);
        btnRemoverEquipamento.setContentAreaFilled(false);
        btnRemoverEquipamento.setFocusPainted(false);
        btnRemoverEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverEquipamentoActionPerformed(evt);
            }
        });

        btnSimular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao_simular.png"))); // NOI18N
        btnSimular.setBorderPainted(false);
        btnSimular.setContentAreaFilled(false);
        btnSimular.setFocusPainted(false);
        btnSimular.setFocusable(false);
        btnSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularActionPerformed(evt);
            }
        });

        btnLimparEspacoTrabalho.setText("Limpar");
        btnLimparEspacoTrabalho.setFocusPainted(false);
        btnLimparEspacoTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparEspacoTrabalhoActionPerformed(evt);
            }
        });

        btnSalvarEspacoTrabalho.setText("Salvar");
        btnSalvarEspacoTrabalho.setFocusPainted(false);
        btnSalvarEspacoTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEspacoTrabalhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlMenuLayout = new javax.swing.GroupLayout(PnlMenu);
        PnlMenu.setLayout(PnlMenuLayout);
        PnlMenuLayout.setHorizontalGroup(
            PnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMenuLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnGirarEquipamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConectarEquipamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoverEquipamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimparEspacoTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvarEspacoTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnSimular)
                .addContainerGap(669, Short.MAX_VALUE))
        );
        PnlMenuLayout.setVerticalGroup(
            PnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMenuLayout.createSequentialGroup()
                .addGroup(PnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRemoverEquipamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConectarEquipamentos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGirarEquipamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 4, Short.MAX_VALUE))
            .addGroup(PnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimular, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnLimparEspacoTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvarEspacoTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlBackgruond.add(PnlMenu);
        PnlMenu.setBounds(0, 30, 1370, 50);

        pnlEspacoTrabalho.setBackground(new java.awt.Color(204, 204, 204));
        pnlEspacoTrabalho.setLayout(null);

        lblNotificacaoDeEstado.setText("Nenhum modo de edição selecionado");
        pnlEspacoTrabalho.add(lblNotificacaoDeEstado);
        lblNotificacaoDeEstado.setBounds(30, 10, 320, 18);

        pnlBackgruond.add(pnlEspacoTrabalho);
        pnlEspacoTrabalho.setBounds(0, 80, 1250, 710);

        PnlBotoes.setBackground(new java.awt.Color(255, 255, 255));

        btnTubulacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Botão tubulação.png"))); // NOI18N
        btnTubulacoes.setBorder(null);
        btnTubulacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTubulacoesActionPerformed(evt);
            }
        });

        btnConexoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Botão conexões.png"))); // NOI18N
        btnConexoes.setBorder(null);
        btnConexoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConexoesActionPerformed(evt);
            }
        });

        btnEquipamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Botão equipamentos.png"))); // NOI18N
        btnEquipamentos.setBorder(null);
        btnEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipamentosActionPerformed(evt);
            }
        });

        btnVavulas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Botão vávulas.png"))); // NOI18N
        btnVavulas.setBorder(null);
        btnVavulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVavulasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlBotoesLayout = new javax.swing.GroupLayout(PnlBotoes);
        PnlBotoes.setLayout(PnlBotoesLayout);
        PnlBotoesLayout.setHorizontalGroup(
            PnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTubulacoes)
                    .addComponent(btnConexoes)
                    .addComponent(btnEquipamentos)
                    .addComponent(btnVavulas))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        PnlBotoesLayout.setVerticalGroup(
            PnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlBotoesLayout.createSequentialGroup()
                .addContainerGap(357, Short.MAX_VALUE)
                .addComponent(btnTubulacoes)
                .addGap(5, 5, 5)
                .addComponent(btnConexoes)
                .addGap(5, 5, 5)
                .addComponent(btnEquipamentos)
                .addGap(5, 5, 5)
                .addComponent(btnVavulas)
                .addGap(288, 288, 288))
        );

        pnlBackgruond.add(PnlBotoes);
        PnlBotoes.setBounds(1250, 0, 120, 820);

        getContentPane().add(pnlBackgruond);
        pnlBackgruond.setBounds(0, 0, 1370, 820);

        setSize(new java.awt.Dimension(1388, 826));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConexoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConexoesActionPerformed
        
        
        this.gerenciarMenuLateral("conexao");
        
        /*
        if(!this._menuFerramentasController.is_menuAberto() || this._menuFerramentasController.is_menuAberto() && !this._menuFerramentasController.get_nomeMenuAberto().equals("Conexões")){
            
            this._menuFerramentasController.abrirMenuFerramentas(this.pnlEspacoTrabalho, this, "Conexões"); 
            
        } else {
            
            this._menuFerramentasController.fecharMenuFerramentas(this.pnlEspacoTrabalho);
            
        }*/
       
    }//GEN-LAST:event_btnConexoesActionPerformed

    private void btnVavulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVavulasActionPerformed
      
        if(!this._menuFerramentasController.is_menuAberto() || this._menuFerramentasController.is_menuAberto() && !this._menuFerramentasController.get_nomeMenuAberto().equals("Válvulas")){
            
            this._menuFerramentasController.abrirMenuFerramentas(this.pnlEspacoTrabalho,this, NomeEquipamento.VALVULA.getString()); 
            
        } else {
            
            this._menuFerramentasController.fecharMenuFerramentas(this.pnlEspacoTrabalho);
            
        }
    }//GEN-LAST:event_btnVavulasActionPerformed

    private void btnEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipamentosActionPerformed
        
        if(!this._menuFerramentasController.is_menuAberto() || this._menuFerramentasController.is_menuAberto() && !this._menuFerramentasController.get_nomeMenuAberto().equals("Equipamentos")){
            
            this._menuFerramentasController.abrirMenuFerramentas(this.pnlEspacoTrabalho,this, "Equipamentos"); 
            
        } else {
            
            this._menuFerramentasController.fecharMenuFerramentas(this.pnlEspacoTrabalho);
            
        }
        
    }//GEN-LAST:event_btnEquipamentosActionPerformed

    private void btnTubulacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTubulacoesActionPerformed
        
        this.gerenciarMenuLateral("tubulacao");
        /*if(!this._menuFerramentasController.is_menuAberto() || this._menuFerramentasController.is_menuAberto() && !this._menuFerramentasController.get_nomeMenuAberto().equals("Tubulações")){
            
            this._menuFerramentasController.abrirMenuFerramentas(this.pnlEspacoTrabalho, this, NomeEquipamento.TUBULACAO.getString()); 
            
        } else {
            
            this._menuFerramentasController.fecharMenuFerramentas(this.pnlEspacoTrabalho);
            
        }*/
        
    }//GEN-LAST:event_btnTubulacoesActionPerformed

    private void btnGirarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirarEquipamentoActionPerformed
        
        this.areaDeTrabalhoController.mudarStatusModoRotacao(
            !this.areaDeTrabalhoController.isEmModoRotacao()
        );
        this.areaDeTrabalhoController.exibirMensagemEstadoDeRotacao(lblNotificacaoDeEstado, 4000);
        
        /*
        Label lblFerramentaSelecionada = (Label) this._menuFerramentasController.getLblFerramentaSelecionadaParaInteracao();
        ImageIcon iconAntigo = (ImageIcon) lblFerramentaSelecionada.getIcon();

        // Convertendo a ToolkitImage para BufferedImage
        BufferedImage bufferedImage = MenuSuperiorController.toBufferedImage(iconAntigo.getImage());

        // Girar a imagem
        ImageIcon iconGirado = MenuSuperiorController.rotate(bufferedImage, 90);

        // Definir a nova imagem girada e redimensionada
        lblFerramentaSelecionada.setIcon(iconGirado);
        lblFerramentaSelecionada.setSize(lblFerramentaSelecionada.getHeight(), lblFerramentaSelecionada.getWidth());
        lblFerramentaSelecionada.setOrientacao(lblFerramentaSelecionada.getOrientacao().equals(Constantes.VERTICAL) ? Constantes.HORIZONTAL : Constantes.VERTICAL);
        // Revalidar e repintar o componente pai
        this.revalidate();
        this.repaint();
        */
        
    }//GEN-LAST:event_btnGirarEquipamentoActionPerformed

    private void btnConectarEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarEquipamentosActionPerformed

        this.areaDeTrabalhoController.mudarStatusModoConexao(
                !this.areaDeTrabalhoController.isEmModoConexao()
        );
        this.areaDeTrabalhoController.exibirMensagemEstadoDeConexao(lblNotificacaoDeEstado, 4000);
        
        /*
        this.botaoConectarController.conectarEquipamentos(
                this._menuFerramentasController.getPilhaConexaoEquipamento().get(0), 
                this._menuFerramentasController.getPilhaConexaoEquipamento().get(1)
        );
        
        this._menuFerramentasController.getPilhaConexaoEquipamento().clear(); // limpa a pilha de ferramentas a serem conectadas.
        */
    }//GEN-LAST:event_btnConectarEquipamentosActionPerformed

    private void btnRemoverEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverEquipamentoActionPerformed
              
    
        emModoRemocao = !emModoRemocao;

        this.areaDeTrabalhoController.mudarStatusModoRemocao(emModoRemocao);
        this.areaDeTrabalhoController.atualizarImagemBotaoRemover(btnRemoverEquipamento);
        this.areaDeTrabalhoController.exibirMensagemEstadoModoDeRemocao(lblNotificacaoDeEstado, 4000);        
        
        emModoConexao = false;
        
    }//GEN-LAST:event_btnRemoverEquipamentoActionPerformed

    private void btnSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularActionPerformed
        
        botaoSimularController.exibirWidgetDeParametrosSimulacao(this.pnlEspacoTrabalho);
        
    }//GEN-LAST:event_btnSimularActionPerformed

    private void btnLimparEspacoTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparEspacoTrabalhoActionPerformed
        
        this.areaDeTrabalhoController.deletarEspacoTrabalho();
        
    }//GEN-LAST:event_btnLimparEspacoTrabalhoActionPerformed

    private void btnSalvarEspacoTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEspacoTrabalhoActionPerformed
      
        this.areaDeTrabalhoController.salvarEspacoTrabalho();
        
    }//GEN-LAST:event_btnSalvarEspacoTrabalhoActionPerformed

    private void gerenciarMenuLateral(String tipoEquipamento){
        
        this.areaDeTrabalhoController.gerenciarMenuLateral(pnlEspacoTrabalho, tipoEquipamento);
        
    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaDeTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaDeTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaDeTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaDeTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaDeTrabalho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabTítulo;
    private javax.swing.JPanel PnlBotoes;
    private javax.swing.JPanel PnlFixo;
    private javax.swing.JPanel PnlMenu;
    private javax.swing.JButton btnConectarEquipamentos;
    private javax.swing.JButton btnConexoes;
    private javax.swing.JButton btnEquipamentos;
    private javax.swing.JButton btnGirarEquipamento;
    private javax.swing.JButton btnLimparEspacoTrabalho;
    private javax.swing.JButton btnRemoverEquipamento;
    private javax.swing.JButton btnSalvarEspacoTrabalho;
    private javax.swing.JButton btnSimular;
    private javax.swing.JButton btnTubulacoes;
    private javax.swing.JButton btnVavulas;
    private javax.swing.JLabel lblNotificacaoDeEstado;
    private javax.swing.JPanel pnlBackgruond;
    private javax.swing.JPanel pnlEspacoTrabalho;
    // End of variables declaration//GEN-END:variables
}
