package br.com.ifba.ipss.view;

import br.com.ifba.ipss.controller.MenuFerramentasController;
import javax.swing.ImageIcon;

/**
 *
 * @author curso
 */
public class PrototipoTela extends javax.swing.JFrame {

    
    // *************************************************//
    // ************** { Variáveis Globais } ************//
    // *************************************************//
    private MenuFerramentasController menuFerramentasController = new MenuFerramentasController();
    
    /**
     * Cria a interface com os componentes iniciais
     */
    public PrototipoTela() {
        
        inicializadorPersonalizado();
        initComponents();
        
    }

    private void inicializadorPersonalizado(){
        
        ImageIcon favicon = new ImageIcon(getClass().getResource("/images/logo.jpg"));
        
        this.setIconImage(favicon.getImage());
        this.setTitle("EduSimLab - Laboratório Virtual de Simulação de Processos");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlAreadeTrabalho = new javax.swing.JPanel();
        PnlFixo = new javax.swing.JPanel();
        LabTítulo = new javax.swing.JLabel();
        PnlMenu = new javax.swing.JPanel();
        PnlFerramentas = new javax.swing.JPanel();
        BtnFerramenta = new javax.swing.JButton();
        PnlExpansão = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlAreadeTrabalho.setBackground(new java.awt.Color(204, 204, 204));
        PnlAreadeTrabalho.setLayout(null);

        PnlFixo.setBackground(new java.awt.Color(0, 102, 51));

        LabTítulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabTítulo.setForeground(new java.awt.Color(255, 255, 255));
        LabTítulo.setText("EduSimLab - Laboratório Virtual de Simulação de Processos");
        PnlFixo.add(LabTítulo);

        PnlAreadeTrabalho.add(PnlFixo);
        PnlFixo.setBounds(0, 0, 1360, 30);

        PnlMenu.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PnlMenuLayout = new javax.swing.GroupLayout(PnlMenu);
        PnlMenu.setLayout(PnlMenuLayout);
        PnlMenuLayout.setHorizontalGroup(
            PnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1360, Short.MAX_VALUE)
        );
        PnlMenuLayout.setVerticalGroup(
            PnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        PnlAreadeTrabalho.add(PnlMenu);
        PnlMenu.setBounds(0, 30, 1360, 30);

        PnlFerramentas.setBackground(new java.awt.Color(255, 255, 255));
        PnlFerramentas.setLayout(new javax.swing.BoxLayout(PnlFerramentas, javax.swing.BoxLayout.LINE_AXIS));

        BtnFerramenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotãoFeramenta.1.1.png"))); // NOI18N
        BtnFerramenta.setBorderPainted(false);
        BtnFerramenta.setContentAreaFilled(false);
        BtnFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFerramentaActionPerformed(evt);
            }
        });
        PnlFerramentas.add(BtnFerramenta);

        PnlAreadeTrabalho.add(PnlFerramentas);
        PnlFerramentas.setBounds(1260, 0, 90, 820);

        PnlExpansão.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PnlExpansãoLayout = new javax.swing.GroupLayout(PnlExpansão);
        PnlExpansão.setLayout(PnlExpansãoLayout);
        PnlExpansãoLayout.setHorizontalGroup(
            PnlExpansãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        PnlExpansãoLayout.setVerticalGroup(
            PnlExpansãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );

        PnlAreadeTrabalho.add(PnlExpansão);
        PnlExpansão.setBounds(1350, 0, 13, 820);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlAreadeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 1362, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlAreadeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1378, 828));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void BtnFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFerramentaActionPerformed
        
        menuFerramentasController.abrirMenuFerramentas();
        
    }//GEN-LAST:event_BtnFerramentaActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrototipoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrototipoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrototipoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrototipoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrototipoTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnFerramenta;
    private javax.swing.JLabel LabTítulo;
    private javax.swing.JPanel PnlAreadeTrabalho;
    private javax.swing.JPanel PnlExpansão;
    private javax.swing.JPanel PnlFerramentas;
    private javax.swing.JPanel PnlFixo;
    private javax.swing.JPanel PnlMenu;
    // End of variables declaration//GEN-END:variables
}
