/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.ifba.ipss.feature.telainicial.menu.widget;

/**
 *
 * @author giovane
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConfig = new javax.swing.JButton();
        btnLoadProject = new javax.swing.JButton();
        btnNewProject = new javax.swing.JButton();
        btnInstructions = new javax.swing.JButton();

        setLayout(null);

        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings.png"))); // NOI18N
        btnConfig.setBorderPainted(false);
        btnConfig.setContentAreaFilled(false);
        add(btnConfig);
        btnConfig.setBounds(430, 240, 110, 100);

        btnLoadProject.setText("Carregar Projeto");
        btnLoadProject.setBorderPainted(false);
        btnLoadProject.setFocusPainted(false);
        add(btnLoadProject);
        btnLoadProject.setBounds(130, 30, 310, 60);

        btnNewProject.setText("Novo Projeto");
        btnNewProject.setBorderPainted(false);
        btnNewProject.setFocusPainted(false);
        add(btnNewProject);
        btnNewProject.setBounds(130, 100, 310, 60);

        btnInstructions.setText("Instruções");
        btnInstructions.setBorderPainted(false);
        btnInstructions.setFocusPainted(false);
        btnInstructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstructionsActionPerformed(evt);
            }
        });
        add(btnInstructions);
        btnInstructions.setBounds(130, 170, 310, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstructionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInstructionsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnInstructions;
    private javax.swing.JButton btnLoadProject;
    private javax.swing.JButton btnNewProject;
    // End of variables declaration//GEN-END:variables
}
