// *************************************************//
// *************** { COMEÇO - Package } ************//
// *************************************************//

package br.com.ifba.ipss.feature.simulationlist.view;

// *************************************************//
// *************** { FIM - Package } ***************//
// *************************************************//

// *************************************************//
// ************ { COMEÇO - Imports } ***************//
// *************************************************//

import br.com.ifba.ipss.feature.simulationlist.controller.SimulationListController;
import br.com.ifba.ipss.helper.PathHelper;
import br.com.ifba.ipss.helper.ScreenHelper;
import br.com.ifba.ipss.infrastructure.manager.ControllerManager;
import br.com.ifba.ipss.theme.ThemeManager;
import br.com.ifba.ipss.util.Constantes;
import static br.com.ifba.ipss.util.Dicionario.tr;

import java.io.IOException;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

// *************************************************//
// ************** { FIM - Imports } ****************//
// *************************************************//

/**
 *
 * @author Giovane Neves
 * @since v0.0.1
 */
public class ListaSimulacoes extends javax.swing.JFrame {

    private final SimulationListController simulationListController;
    
    String typedKeyCharList = "";
    
    /**
     * Creates new form ListaSimulacoes
     */
    public ListaSimulacoes() {
                
        initComponents();
        
        simulationListController = new SimulationListController(this);

        customIntl();

    }
    
    /**
     * Inicializador Personalizado da Tela
     * 
     * @author Giovane Neves
     */
    private void customIntl(){
        
        this.pnlBackground.setBackground(ThemeManager.getColor("secondary"));
        
        this.btnSearch.setBackground(ThemeManager.getColor("primary"));
        this.btnSearch.setForeground(ThemeManager.getColor("secondary"));
        this.btnSearch.setText(tr(this.btnSearch.getText()));
        
        ImageIcon favicon = new ImageIcon(getClass().getResource(Constantes.CAMINHO_LOGO));
        this.simulationListController.defineScreenFavicon(favicon.getImage());
        this.simulationListController.defineScreenTitle();
        
        loadJsonFiles();
    }
    
    private void loadJsonFiles(){
        
        DefaultListModel<String> model = new DefaultListModel<>();
        Path filesDir = Paths.get(PathHelper.FILES_PATH);
        
        try (DirectoryStream<Path> stream = Files.newDirectoryStream(filesDir, "*.json")) {
            
            for (Path entry : stream) {
                if(entry.getFileName().toString().equals("tools.json") || entry.getFileName().toString().equals("ferramentas.json"))
                    continue;
                model.addElement(entry.getFileName().toString());
            }
            
        } catch (IOException e) {
            
            e.printStackTrace();
            
        }
        
        listWorkspaces.setModel(model);
         
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        txtFieldSearchBox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listWorkspaces = new javax.swing.JList<>();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnlBackground.setLayout(null);

        txtFieldSearchBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldSearchBoxKeyTyped(evt);
            }
        });
        pnlBackground.add(txtFieldSearchBox);
        txtFieldSearchBox.setBounds(60, 30, 300, 24);

        listWorkspaces.setForeground(new java.awt.Color(0, 102, 51));
        listWorkspaces.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "workspace.json", "area_de_teste.json" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listWorkspaces.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listWorkspacesMouseClicked(evt);
            }
        });
        listWorkspaces.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listWorkspacesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listWorkspaces);

        pnlBackground.add(jScrollPane1);
        jScrollPane1.setBounds(60, 70, 410, 380);

        btnSearch.setText("buscar");
        btnSearch.setBorderPainted(false);
        btnSearch.setFocusPainted(false);
        pnlBackground.add(btnSearch);
        btnSearch.setBounds(370, 30, 100, 24);

        getContentPane().add(pnlBackground);
        pnlBackground.setBounds(-4, 0, 510, 460);

        setSize(new java.awt.Dimension(520, 493));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void listWorkspacesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listWorkspacesValueChanged
       
        dispose();
        ScreenHelper.pegarTela(ScreenHelper.AREA_TRABALHO, this.listWorkspaces.getModel().getElementAt(this.listWorkspaces.getSelectedIndex())).setVisible(true);
        
    }//GEN-LAST:event_listWorkspacesValueChanged

    private void listWorkspacesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listWorkspacesMouseClicked
        
    }//GEN-LAST:event_listWorkspacesMouseClicked

    private void txtFieldSearchBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldSearchBoxKeyTyped
        
        updateTypedKeyCharList(String.valueOf(evt.getKeyChar()), typedKeyCharList);
        
    }//GEN-LAST:event_txtFieldSearchBoxKeyTyped

    private void updateTypedKeyCharList(String typedChar, String list){
        
        typedKeyCharList = typedKeyCharList.concat(typedChar);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaSimulacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaSimulacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaSimulacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaSimulacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaSimulacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listWorkspaces;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JTextField txtFieldSearchBox;
    // End of variables declaration//GEN-END:variables
}
