// *************************************************//
// *************** { COMEÇO - Package } ************//
// *************************************************//

package br.com.ifba.ipss.feature.parametrossimulacao.widget;

// *************************************************//
// *************** { FIM - Package } ***************//
// *************************************************//

// *************************************************//
// ************ { COMEÇO - Imports } ***************//
// *************************************************//

import br.com.ifba.ipss.feature.parametrossimulacao.controller.ParametrosSimulacaoController;
import br.com.ifba.ipss.helper.FormulaHelper;
import br.com.ifba.ipss.infrastructure.manager.ControllerManager;
import br.com.ifba.ipss.util.Constantes;

// *************************************************//
// ************** { FIM - Imports } ****************//
// *************************************************//

/**
 *
 * @author Lorrane554
 * @since V0.0.1
 */
public class ParametrosDaSimulacao extends javax.swing.JPanel {

    // INFO: Atributos
    private final ParametrosSimulacaoController parametrosSimulacaoController;
    
    private double coeficienteAtrito;
    private double viscosidade;
    private double velocidade;
    private double diametroInterno;
    
    /**
     * Construtor da Classe
     * 
     * @author Giovane Neves
     * @since V0.0.1
     */
    public ParametrosDaSimulacao() {
        
        initComponents();
        
        parametrosSimulacaoController = ControllerManager.find(Constantes.PARAMETROS_SIMULACAO_CONTROLLER);
    
    } // ParametrosDaSimulacao

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCoeficienteAtrito = new javax.swing.JLabel();
        jSpinViscosidadeCinematica = new javax.swing.JSpinner();
        jSpinVelocidade = new javax.swing.JSpinner();
        jSpinCoeficienteAtrito = new javax.swing.JSpinner();
        btnSimulation = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSpinDiametroInterno1 = new javax.swing.JSpinner();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Parâmetros da simulação");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 10, 160, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 110, 140, 0);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Viscosidade cinemática (m²/s)");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 40, 150, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Velocidade (m/s)");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 80, 130, 15);

        lblCoeficienteAtrito.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblCoeficienteAtrito.setText("Coeficiente de Atrito");
        jPanel1.add(lblCoeficienteAtrito);
        lblCoeficienteAtrito.setBounds(50, 140, 160, 15);

        jSpinViscosidadeCinematica.setModel(new javax.swing.SpinnerNumberModel(0.1d, 0.1d, 100.0d, 1.0d));
        jPanel1.add(jSpinViscosidadeCinematica);
        jSpinViscosidadeCinematica.setBounds(220, 40, 75, 24);

        jSpinVelocidade.setModel(new javax.swing.SpinnerNumberModel(0.1d, 0.1d, 100.0d, 1.0d));
        jPanel1.add(jSpinVelocidade);
        jSpinVelocidade.setBounds(220, 70, 75, 24);

        jSpinCoeficienteAtrito.setModel(new javax.swing.SpinnerNumberModel(0.1d, 0.1d, 100.0d, 1.0d));
        jPanel1.add(jSpinCoeficienteAtrito);
        jSpinCoeficienteAtrito.setBounds(220, 130, 75, 24);

        btnSimulation.setBackground(new java.awt.Color(204, 204, 204));
        btnSimulation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Botão simulação.2.png"))); // NOI18N
        btnSimulation.setBorder(null);
        btnSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimulationActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimulation);
        btnSimulation.setBounds(110, 170, 100, 40);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(290, 10, 20, 16);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Diâmetro interno do tubo (mm)");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 110, 160, 15);

        jSpinDiametroInterno1.setModel(new javax.swing.SpinnerNumberModel(0.1d, 0.1d, 100.0d, 1.0d));
        jPanel1.add(jSpinDiametroInterno1);
        jSpinDiametroInterno1.setBounds(220, 100, 75, 24);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 320, 220);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimulationActionPerformed
        
        coeficienteAtrito = (double) jSpinCoeficienteAtrito.getValue();
        velocidade = (double) jSpinVelocidade.getValue();
        viscosidade =  (double) jSpinViscosidadeCinematica.getValue();
        diametroInterno = (double) jSpinCoeficienteAtrito.getValue();
        
        parametrosSimulacaoController.setCoeficienteAtrito(coeficienteAtrito);
        parametrosSimulacaoController.setVelocidade(velocidade);
        parametrosSimulacaoController.setViscosidade(viscosidade);
        parametrosSimulacaoController.setDiametroInterno(diametroInterno);
        
        parametrosSimulacaoController.setNumeroReynold(FormulaHelper.EQUACAO_DE_REYNOLD(velocidade, diametroInterno, viscosidade));
        parametrosSimulacaoController.setEscoamento(FormulaHelper.VERIFICAR_ESCOAMENTO(parametrosSimulacaoController.getNumeroReynold()));
        
        parametrosSimulacaoController.setPerdaCarga();
        
        this.getParent().add(parametrosSimulacaoController.createResultsWidget());
        this.getParent().revalidate();
        this.getParent().repaint();
        
    }//GEN-LAST:event_btnSimulationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimulation;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinCoeficienteAtrito;
    private javax.swing.JSpinner jSpinDiametroInterno1;
    private javax.swing.JSpinner jSpinVelocidade;
    private javax.swing.JSpinner jSpinViscosidadeCinematica;
    private javax.swing.JLabel lblCoeficienteAtrito;
    // End of variables declaration//GEN-END:variables
}
