/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author curso
 */
public class AreaDeTrabalho2 extends javax.swing.JFrame {

    /**
     * Creates new form AreaDeTrabalho2
     */
    public AreaDeTrabalho2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFixo = new javax.swing.JPanel();
        LabTítulo = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        lblTravessão = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlFerramentas = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pnlExtensao = new javax.swing.JPanel();
        pnlBombas = new javax.swing.JPanel();
        lblBombas = new javax.swing.JLabel();
        pnlVávulas = new javax.swing.JPanel();
        lblVavulas = new javax.swing.JLabel();
        pnlReatores = new javax.swing.JPanel();
        lblReatores = new javax.swing.JLabel();
        pnlConecxões = new javax.swing.JPanel();
        lblConexoes = new javax.swing.JLabel();
        pnlTubulação = new javax.swing.JPanel();
        lblTubulcao = new javax.swing.JLabel();
        pnlManômetros = new javax.swing.JPanel();
        lblManometros = new javax.swing.JLabel();
        pnlOutros = new javax.swing.JPanel();
        lblOutros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1362, 820));
        getContentPane().setLayout(null);

        pnlFixo.setBackground(new java.awt.Color(0, 102, 51));
        pnlFixo.setForeground(new java.awt.Color(0, 102, 51));

        LabTítulo.setBackground(new java.awt.Color(255, 255, 255));
        LabTítulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabTítulo.setForeground(new java.awt.Color(255, 255, 255));
        LabTítulo.setText("EduSimLab - Laboratório Virtual de Simulação de Processos");

        javax.swing.GroupLayout pnlFixoLayout = new javax.swing.GroupLayout(pnlFixo);
        pnlFixo.setLayout(pnlFixoLayout);
        pnlFixoLayout.setHorizontalGroup(
            pnlFixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFixoLayout.createSequentialGroup()
                .addContainerGap(422, Short.MAX_VALUE)
                .addComponent(LabTítulo)
                .addGap(615, 615, 615))
        );
        pnlFixoLayout.setVerticalGroup(
            pnlFixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFixoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabTítulo)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(pnlFixo);
        pnlFixo.setBounds(0, 0, 1362, 30);

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N

        lblTravessão.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Travessão.png"))); // NOI18N

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addContainerGap(1254, Short.MAX_VALUE)
                .addComponent(lblTravessão, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblExit)
                .addGap(437, 437, 437))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTravessão, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblExit)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(pnlMenu);
        pnlMenu.setBounds(-8, 30, 1780, 30);

        pnlFerramentas.setBackground(new java.awt.Color(255, 255, 255));
        pnlFerramentas.setLayout(new javax.swing.BoxLayout(pnlFerramentas, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotãoFeramenta.1.1.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        pnlFerramentas.add(jButton1);

        getContentPane().add(pnlFerramentas);
        pnlFerramentas.setBounds(1260, 30, 90, 820);

        pnlExtensao.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlExtensaoLayout = new javax.swing.GroupLayout(pnlExtensao);
        pnlExtensao.setLayout(pnlExtensaoLayout);
        pnlExtensaoLayout.setHorizontalGroup(
            pnlExtensaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        pnlExtensaoLayout.setVerticalGroup(
            pnlExtensaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(pnlExtensao);
        pnlExtensao.setBounds(1350, 40, 16, 430);

        pnlBombas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblBombas.setText("Bombas");

        javax.swing.GroupLayout pnlBombasLayout = new javax.swing.GroupLayout(pnlBombas);
        pnlBombas.setLayout(pnlBombasLayout);
        pnlBombasLayout.setHorizontalGroup(
            pnlBombasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBombasLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblBombas)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        pnlBombasLayout.setVerticalGroup(
            pnlBombasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBombasLayout.createSequentialGroup()
                .addComponent(lblBombas)
                .addGap(0, 740, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBombas);
        pnlBombas.setBounds(0, 60, 180, 760);

        pnlVávulas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblVavulas.setText("Vávulas");

        javax.swing.GroupLayout pnlVávulasLayout = new javax.swing.GroupLayout(pnlVávulas);
        pnlVávulas.setLayout(pnlVávulasLayout);
        pnlVávulasLayout.setHorizontalGroup(
            pnlVávulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVávulasLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblVavulas)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        pnlVávulasLayout.setVerticalGroup(
            pnlVávulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVávulasLayout.createSequentialGroup()
                .addComponent(lblVavulas)
                .addGap(0, 740, Short.MAX_VALUE))
        );

        getContentPane().add(pnlVávulas);
        pnlVávulas.setBounds(180, 60, 180, 760);

        pnlReatores.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblReatores.setText("Reatores");

        javax.swing.GroupLayout pnlReatoresLayout = new javax.swing.GroupLayout(pnlReatores);
        pnlReatores.setLayout(pnlReatoresLayout);
        pnlReatoresLayout.setHorizontalGroup(
            pnlReatoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReatoresLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(lblReatores)
                .addGap(66, 66, 66))
        );
        pnlReatoresLayout.setVerticalGroup(
            pnlReatoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReatoresLayout.createSequentialGroup()
                .addComponent(lblReatores)
                .addGap(0, 740, Short.MAX_VALUE))
        );

        getContentPane().add(pnlReatores);
        pnlReatores.setBounds(360, 60, 180, 760);

        pnlConecxões.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblConexoes.setText("Conexões");

        javax.swing.GroupLayout pnlConecxõesLayout = new javax.swing.GroupLayout(pnlConecxões);
        pnlConecxões.setLayout(pnlConecxõesLayout);
        pnlConecxõesLayout.setHorizontalGroup(
            pnlConecxõesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConecxõesLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(lblConexoes)
                .addGap(66, 66, 66))
        );
        pnlConecxõesLayout.setVerticalGroup(
            pnlConecxõesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConecxõesLayout.createSequentialGroup()
                .addComponent(lblConexoes)
                .addGap(0, 740, Short.MAX_VALUE))
        );

        getContentPane().add(pnlConecxões);
        pnlConecxões.setBounds(540, 60, 180, 760);

        pnlTubulação.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTubulcao.setText("Tubulação");

        javax.swing.GroupLayout pnlTubulaçãoLayout = new javax.swing.GroupLayout(pnlTubulação);
        pnlTubulação.setLayout(pnlTubulaçãoLayout);
        pnlTubulaçãoLayout.setHorizontalGroup(
            pnlTubulaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTubulaçãoLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblTubulcao)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        pnlTubulaçãoLayout.setVerticalGroup(
            pnlTubulaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTubulaçãoLayout.createSequentialGroup()
                .addComponent(lblTubulcao)
                .addGap(0, 740, Short.MAX_VALUE))
        );

        getContentPane().add(pnlTubulação);
        pnlTubulação.setBounds(720, 60, 180, 760);

        pnlManômetros.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblManometros.setText("Manômetros");

        javax.swing.GroupLayout pnlManômetrosLayout = new javax.swing.GroupLayout(pnlManômetros);
        pnlManômetros.setLayout(pnlManômetrosLayout);
        pnlManômetrosLayout.setHorizontalGroup(
            pnlManômetrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManômetrosLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lblManometros)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pnlManômetrosLayout.setVerticalGroup(
            pnlManômetrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManômetrosLayout.createSequentialGroup()
                .addComponent(lblManometros)
                .addGap(0, 740, Short.MAX_VALUE))
        );

        getContentPane().add(pnlManômetros);
        pnlManômetros.setBounds(900, 60, 180, 760);

        pnlOutros.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblOutros.setText("Outros");

        javax.swing.GroupLayout pnlOutrosLayout = new javax.swing.GroupLayout(pnlOutros);
        pnlOutros.setLayout(pnlOutrosLayout);
        pnlOutrosLayout.setHorizontalGroup(
            pnlOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOutrosLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblOutros)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        pnlOutrosLayout.setVerticalGroup(
            pnlOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOutrosLayout.createSequentialGroup()
                .addComponent(lblOutros)
                .addGap(0, 740, Short.MAX_VALUE))
        );

        getContentPane().add(pnlOutros);
        pnlOutros.setBounds(1080, 60, 180, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaDeTrabalho2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaDeTrabalho2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaDeTrabalho2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaDeTrabalho2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaDeTrabalho2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabTítulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBombas;
    private javax.swing.JLabel lblConexoes;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblManometros;
    private javax.swing.JLabel lblOutros;
    private javax.swing.JLabel lblReatores;
    private javax.swing.JLabel lblTravessão;
    private javax.swing.JLabel lblTubulcao;
    private javax.swing.JLabel lblVavulas;
    private javax.swing.JPanel pnlBombas;
    private javax.swing.JPanel pnlConecxões;
    private javax.swing.JPanel pnlExtensao;
    private javax.swing.JPanel pnlFerramentas;
    private javax.swing.JPanel pnlFixo;
    private javax.swing.JPanel pnlManômetros;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlOutros;
    private javax.swing.JPanel pnlReatores;
    private javax.swing.JPanel pnlTubulação;
    private javax.swing.JPanel pnlVávulas;
    // End of variables declaration//GEN-END:variables
}
