package br.com.ifba.ipss.feature.auth.views;

import br.com.ifba.ipss.theme.ThemeManager;
import static br.com.ifba.ipss.util.Dicionario.tr;

/**
 *
 * @author Giovane Neves
 * @since V0.0.1
 */
public class LoginView extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public LoginView() {
        initComponents();
    }
    
    public void customIntl(){
        
        this.btnLogin.setBackground(ThemeManager.getColor("primary"));
        this.btnLogin.setForeground(ThemeManager.getColor("secondary"));
        this.btnLogin.setText(tr(this.btnLogin.getText()));
        
        this.lblViewTitle.setText(this.lblViewTitle.getText());
        
        this.txtUsername.setText(this.txtUsername.getText());
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewIcon = new javax.swing.JLabel();
        lblViewTitle = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblViewIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scientist.png"))); // NOI18N
        add(lblViewIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        lblViewTitle.setText("acesso_orientador");
        add(lblViewTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        txtUsername.setText("nome_usuario");
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 420, 40));

        txtPassword.setText("jPasswordField1");
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 420, 40));

        btnLogin.setText("entrar");
        add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 210, 50));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblViewIcon;
    private javax.swing.JLabel lblViewTitle;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
